spring.application.name=HMS
spring.datasource.url= jdbc:postgresql://localhost:5432// Your postgres db name
 spring.datasource.username= // Your postgreSQL username
 spring.datasource.password= //Your postgreSQL password
 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
